# Generated by Django 5.1.5 on 2025-04-04 10:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен бота')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_organization_name')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('engine_type', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('groups', models.ManyToManyField(blank=True, related_name='orguser_groups', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='orguser_permissions', to='auth.permission', verbose_name='Разрешения')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Пользователь организации',
                'verbose_name_plural': 'Пользователи организаций',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('status', models.CharField(blank=True, choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('error', 'Ошибка')], max_length=50, null=True, verbose_name='Статус')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Запрос отчёта',
                'verbose_name_plural': 'Запросы отчётов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('media_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип медиа')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
                ('size', models.IntegerField(blank=True, default=0, null=True, verbose_name='Размер')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('type', models.CharField(blank=True, choices=[('raw', 'Сырые данные'), ('auto', 'Данные об автомобилях')], max_length=50, null=True, verbose_name='Тип файла')),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Хэш файла')),
                ('report_query', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reportquery', verbose_name='Запрос отчёта')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='CarConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('winter_volume', models.FloatField(blank=True, null=True, verbose_name='Зимний расход')),
                ('summer_volume', models.FloatField(blank=True, null=True, verbose_name='Летний расход')),
                ('valid_period', models.DateField(blank=True, null=True, verbose_name='Период действия')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Расход топлива',
                'verbose_name_plural': 'Расходы топлива',
                'ordering': ['car__name', 'valid_period'],
                'indexes': [models.Index(fields=['car', 'valid_period'], name='idx_carconsumption_car_period')],
            },
        ),
        migrations.CreateModel(
            name='CarReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('volume', models.IntegerField(verbose_name='Объём')),
                ('status', models.BooleanField(verbose_name='Статус утечки')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Отчёт об автомобиле',
                'verbose_name_plural': 'Отчёты об автомобилях',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['car', 'datetime'], name='idx_carreport_car_datetime')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('car', models.ManyToManyField(to='core.car', verbose_name='Автомобили')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['fullname'],
                'indexes': [models.Index(fields=['fullname', 'phone'], name='idx_driver_fullname_phone')],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['name', 'organization'], name='idx_car_name_org'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['id'], name='idx_car_id'),
        ),
        migrations.AddIndex(
            model_name='orguser',
            index=models.Index(fields=['username', 'org'], name='idx_orguser_username_org'),
        ),
        migrations.AddIndex(
            model_name='reportquery',
            index=models.Index(fields=['organization', 'status'], name='idx_reportquery_org_status'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['type', 'report_query'], name='idx_media_type_query'),
        ),
    ]
