"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
import warnings

from django.urls import reverse_lazy
from dotenv import load_dotenv
from influxdb_client.client.warnings import MissingPivotFunction

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment
load_dotenv()
warnings.simplefilter("ignore", MissingPivotFunction)

# ======================
# CORE DJANGO SETTINGS
# ======================
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split()
ROOT_URLCONF = 'app.urls'
WSGI_APPLICATION = 'app.wsgi.application'
AUTH_USER_MODEL = 'core.OrgUser'
APPEND_SLASH = False
# ======================
# APPLICATION DEFINITION
# ======================
INSTALLED_APPS = [
    'unfold.contrib.import_export',
    'unfold.contrib.filters',
    'django_celery_beat',
    'unfold',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'core.apps.AppConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'django_filters'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

# ======================
# TEMPLATES
# ======================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ======================
# DATABASE
# ======================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASS'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT'),
        'CONN_MAX_AGE': 120,
        'OPTIONS': {
            'connect_timeout': 60,
        }
    }
}

# ======================
# PASSWORD VALIDATION
# ======================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ======================
# INTERNATIONALIZATION
# ======================
LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.getenv('TIME_ZONE', 'Europe/Moscow')
USE_I18N = True
USE_TZ = True

# ======================
# STATIC & MEDIA FILES
# ======================
STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================
# CORS SETTINGS
# ======================
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ORIGIN_WHITELIST = os.getenv('CORS_ORIGIN_WHITELIST', '').split()
CORS_ALLOW_METHODS = os.getenv('CORS_ALLOW_METHODS', '').split() or [
    'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'
]
CORS_ALLOW_HEADERS = os.getenv('CORS_ALLOW_HEADERS', '').split() or [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with'
]
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True') == 'True'

# ======================
# SECURITY SETTINGS
# ======================
##TODO: Все настройки с CRSF для работы с куки надо расскоментить
# CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split()
# CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
# SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
# CSRF_COOKIE_SAMESITE = 'Lax'
# SESSION_COOKIE_SAMESITE = 'Lax'

# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'False'
# SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
# SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
# SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
# SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'
# SECURE_CONTENT_TYPE_NOSNIFF = os.getenv('SECURE_CONTENT_TYPE_NOSNIFF', 'True') == 'True'
# SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER', 'True') == 'True'
# X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

# ======================
# REST FRAMEWORK
# ======================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=12),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ======================
# KEYDB CONFIG
# ======================
KEYDB_CONFIG = {
    'HOST': os.getenv('KEYDB_HOST', 'fuel-patrol-keydb'),
    'PORT': int(os.getenv('KEYDB_PORT', '6379')),
    'PASSWORD': os.getenv('KEYDB_PASSWORD', 'roottoor'),
    'DECODE_RESPONSES': True,
    'DB': int(os.getenv('KEYDB_DB', '0'))
}

# ======================
# CELERY SETTINGS
# ======================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL',
                              f"redis://:{KEYDB_CONFIG['PASSWORD']}@{KEYDB_CONFIG['HOST']}:{KEYDB_CONFIG['PORT']}/1")
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND',
                                  f"redis://:{KEYDB_CONFIG['PASSWORD']}@{KEYDB_CONFIG['HOST']}:{KEYDB_CONFIG['PORT']}/1")
CELERY_ACCEPT_CONTENT = os.getenv('CELERY_ACCEPT_CONTENT', 'pickle').split() or ['pickle']
CELERY_TASK_SERIALIZER = os.getenv('CELERY_TASK_SERIALIZER', 'pickle')
CELERY_RESULT_SERIALIZER = os.getenv('CELERY_RESULT_SERIALIZER', 'pickle')
CELERY_BROKER_TRANSPORT_OPTIONS = {'DIMvisibility_timeout': 3600}
CELERY_BEAT_SCHEDULER = os.getenv('CELERY_BEAT_SCHEDULER', 'django_celery_beat.schedulers:DatabaseScheduler')
CELERY_RESULT_EXPIRES = 60 * 60

# ======================
# INFLUXDB CONFIG
# ======================
INFLUXDB_CONFIG = {
    'URL': os.getenv('INFLUXDB_URL', 'http://127.0.0.1:8086'),
    'TOKEN': os.getenv('INFLUXDB_TOKEN',
                       'eBBaYUo1pKCxXqweKlcGON17ghZq6AMcjwcswZMdqKzki23J_Tl_0GkS5GK558VvxwOyh-qO9ioDpAVUNY593Q=='),
    'ORG': os.getenv('INFLUXDB_ORG', 'fuel_patrol'),
    'BUCKET': os.getenv('INFLUXDB_BUCKET', 'test_fuel'),
    'TIMEOUT': int(os.getenv('INFLUXDB_TIMEOUT', '10000')),
    'WRITE_OPTIONS': {
        'batch_size': int(os.getenv('INFLUXDB_BATCH_SIZE', '1000')),
        'flush_interval': int(os.getenv('INFLUXDB_FLUSH_INTERVAL', '1000')),
    }
}

# ======================
# LOGGING
# ======================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# ======================
# UNFOLD ADMIN SETTINGS
# ======================
UNFOLD = {
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Организации и пользователи",
                "collapsible": True,
                "items": [
                    {
                        "title": "Организации",
                        "icon": "business",
                        "link": reverse_lazy("admin:core_organization_changelist"),
                    },
                    {
                        "title": "Пользователи",
                        "icon": "person",
                        "link": reverse_lazy("admin:core_orguser_changelist"),
                    },
                    {
                        "title": "Уведомления",
                        "icon": "notifications",
                        "link": reverse_lazy("admin:core_corenotification_changelist"),
                    },
                    {
                        "title": "Языки",
                        "icon": "language",
                        "link": reverse_lazy("admin:core_language_changelist"),
                    },
                    {
                        "title": "Телеграм-пользователи",
                        "icon": "chat",
                        "link": reverse_lazy("admin:core_telegramuser_changelist"),
                    },
                ],
            },
            {
                "title": "Автопарк",
                "collapsible": True,
                "items": [
                    {
                        "title": "Автомобили",
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:core_car_changelist"),
                    },
                    {
                        "title": "Подразделения",
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:core_carunit_changelist"),
                    },
                    {
                        "title": "Списки машин",
                        "icon": "list",
                        "link": reverse_lazy("admin:core_usercarlist_changelist"),
                    },
                    {
                        "title": "Первичные данные",
                        "icon": "storage",
                        "link": reverse_lazy("admin:core_carprimary_changelist"),
                    },
                    {
                        "title": "Водители",
                        "icon": "drive_eta",
                        "link": reverse_lazy("admin:core_driver_changelist"),
                    },
                    {
                        "title": "Расход топлива",
                        "icon": "local_gas_station",
                        "link": reverse_lazy("admin:core_carconsumption_changelist"),
                    },
                    {
                        "title": "Статистика парсинга",
                        "icon": "manage_search",
                        "link": reverse_lazy("admin:core_parsingcarstats_changelist"),
                    },
                ],
            },
            {
                "title": "Отчёты и мониторинг",
                "collapsible": True,
                "items": [
                    {
                        "title": "Запросы отчётов",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:core_reportquery_changelist"),
                    },
                    {
                        "title": "Детали выполнения",
                        "icon": "query_stats",
                        "link": reverse_lazy("admin:core_reportquerydetails_changelist"),
                    },
                    {
                        "title": "Отчёты автомобилей",
                        "icon": "summarize",
                        "link": reverse_lazy("admin:core_carreport_changelist"),
                    },
                    {
                        "title": "Отчёты по топливу/заправке",
                        "icon": "local_gas_station",
                        "link": reverse_lazy("admin:core_carfuelreport_changelist"),
                    },
                    {
                        "title": "Отчёты по пробегам",
                        "icon": "route",
                        "link": reverse_lazy("admin:core_carmileagereport_changelist"),
                    },
                    {
                        "title": "Предобработанные данные",
                        "icon": "data_object",
                        "link": reverse_lazy("admin:core_computeddata_changelist"),
                    },
                    {
                        "title": "Ошибочные данные",
                        "icon": "error_outline",
                        "link": reverse_lazy("admin:core_carbaddata_changelist"),
                    },
                    {
                        "title": "Логи расчетов API",
                        "icon": "terminal",
                        "link": reverse_lazy("admin:core_apicalculationlog_changelist"),
                    },
                ],
            },
            {
                "title": "Датчики",
                "collapsible": True,
                "items": [
                    {
                        "title": "Ключи датчиков",
                        "icon": "vpn_key",
                        "link": reverse_lazy("admin:core_sensorskey_changelist"),
                    },
                    {
                        "title": "Значения датчиков",
                        "icon": "sensors",
                        "link": reverse_lazy("admin:core_sensorsvalues_changelist"),
                    },
                    {
                        "title": "Локализации",
                        "icon": "translate",
                        "link": reverse_lazy("admin:core_sensorskeylocalization_changelist"),
                    },
                ],
            },
            {
                "title": "Поставщики данных",
                "collapsible": True,
                "items": [
                    {
                        "title": "Поставщики данных",
                        "icon": "cloud_upload",
                        "link": reverse_lazy("admin:core_dataprovider_changelist"),
                    },
                ],
            },
            {
                "title": "Задачи Celery",
                "collapsible": True,
                "items": [
                    {
                        "title": "Периодические задачи",
                        "icon": "task",
                        "link": reverse_lazy("admin:django_celery_beat_periodictask_changelist"),
                    },
                    {
                        "title": "Cron-графики",
                        "icon": "update",
                        "link": reverse_lazy("admin:django_celery_beat_crontabschedule_changelist"),
                    },
                    {
                        "title": "Интервалы",
                        "icon": "arrow_range",
                        "link": reverse_lazy("admin:django_celery_beat_intervalschedule_changelist"),
                    },
                    {
                        "title": "Солнечные графики",
                        "icon": "sunny",
                        "link": reverse_lazy("admin:django_celery_beat_solarschedule_changelist"),
                    },
                    {
                        "title": "Графики по времени",
                        "icon": "schedule",
                        "link": reverse_lazy("admin:django_celery_beat_clockedschedule_changelist"),
                    },
                ],
            },
            {
                "title": "DevOps",
                "collapsible": True,
                "items": [
                    {
                        "title": "Службы Systemd",
                        "icon": "terminal",
                        "link": reverse_lazy("admin:core_unitservice_changelist"),
                    },
                ],
            },
        ],
    },
}

# ======================
# SWAGGER SETTINGS
# ======================
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Введите токен в формате: Bearer <токен>',
        }
    },
    'USE_SESSION_AUTH': False,
}

# ======================
# GRAFANA CONFIG
# ======================
GRAFANA_CONFIG = {
    'URL': os.getenv('GRAFANA_URL', 'http://fuel-patrol-grafana:3000'),
    'ADMIN_USER': os.getenv('GRAFANA_ADMIN_USER', 'admin'),
    'ADMIN_PASSWORD': os.getenv('GRAFANA_ADMIN_PASSWORD', 'admin'),
}

# ======================
# DOCKER CONFIG
# ======================
DOCKER_CONFIG = {
    'SERVICE_NAME': 'fuel-patrol',
    'NETWORK_NAME': 'fuel-patrol-network',
    'API_CONTAINER': 'fuel-patrol-api',
    'DB_CONTAINER': 'fuel-patrol-db',
    'REDIS_CONTAINER': 'fuel-patrol-redis',
    'INFLUXDB_CONTAINER': 'fuel-patrol-influxdb'
}

BASE_URL = os.getenv('BASE_URL', 'http://127.0.0.1:8000')

DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000
