"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from django.conf.global_settings import APPEND_SLASH
from django.urls import reverse_lazy
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

load_dotenv()


SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split()

# CORS
CORS_ORIGIN_ALLOW_ALL = True

##CORS_ORIGIN_WHITELIST = os.getenv('CORS_ORIGINS', '127.0.0.1:8000 127.0.0.1:3000').split()

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Application definition
INSTALLED_APPS = [
    'unfold.contrib.import_export',
    'unfold.contrib.filters',
    'django_celery_beat',
    'unfold',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'core.apps.AppConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'django_filters'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]


ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database
DATABASES = {
    'default': {
        "NAME": os.getenv('POSTGRES_DB', 'fuel'),
        "ENGINE": "django.db.backends.postgresql",
        "USER": os.getenv('POSTGRES_USER', 'root'),
        "PASSWORD": os.getenv('POSTGRES_PASS', 'roottoor'),
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Media files
MEDIA_URL = '/media/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery settings
REDIS_USER = os.getenv("KEYDB_USER", "default")
REDIS_PASS = os.getenv("REDIS_PASSWORD", "roottoor")
REDIS_HOST = os.getenv("KEYDB_HOST", "127.0.0.1")
REDIS_PORT = os.getenv("KEYDB_PORT", "6379")
REDIS_DB = os.getenv("KEYDB_DB", "0")

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", f"redis://{REDIS_USER}:{REDIS_PASS}@{REDIS_HOST}:{REDIS_PORT}/1")
CELERY_RESULT_BACKEND = os.getenv("CELERY_BROKER_URL", f"redis://{REDIS_USER}:{REDIS_PASS}@{REDIS_HOST}:{REDIS_PORT}/1")
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}

CELERY_ACCEPT_CONTENT = ["pickle"]
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_RESULT_EXPIRES = 60 * 60

# Celery Flower settings
CELERY_FLOWER_USER = os.getenv("CELERY_FLOWER_USER", "admin")
CELERY_FLOWER_PASSWORD = os.getenv("CELERY_FLOWER_PASSWORD", "admin")
CELERY_FLOWER_PORT = os.getenv("CELERY_FLOWER_PORT", "5555")
CELERY_FLOWER_ADDRESS = os.getenv("CELERY_FLOWER_ADDRESS", "127.0.0.1")


# Custom admin settings
UNFOLD = {
    "TABS": [
        {
            "models": (
                "core.organization",
                "core.orguser",
                "core.reportquery",
                "core.media",
            ),
            "items": [
                {
                    "title": "Организации",
                    "link": reverse_lazy("admin:core_organization_changelist"),
                },
                {
                    "title": "Пользователи",
                    "link": reverse_lazy("admin:core_orguser_changelist"),
                },
                {
                    "title": "Запросы отчетов",
                    "link": reverse_lazy("admin:core_reportquery_changelist"),
                },
                {
                    "title": "Медиафайлы",
                    "link": reverse_lazy("admin:core_media_changelist"),
                },
            ],
        },
        {
            "models": (
                "core.car",
                "core.carreport",
                "core.carconsumption",
                "core.driver",
                "core.drivercar",
            ),
            "items": [
                {
                    "title": "Автомобили",
                    "link": reverse_lazy("admin:core_car_changelist"),
                },
                {
                    "title": "Отчеты об автомобилях",
                    "link": reverse_lazy("admin:core_carreport_changelist"),
                },
                {
                    "title": "Расход топлива",
                    "link": reverse_lazy("admin:core_carconsumption_changelist"),
                },
                {
                    "title": "Водители",
                    "link": reverse_lazy("admin:core_driver_changelist"),
                },
                {
                    "title": "Назначения водителей-автомобилей",
                    "link": reverse_lazy("admin:core_drivercar_changelist"),
                },
            ],
        },
        {
            "models": (
                "core.dataprovider",
            ),
            "items": [
                {
                    "title": "Поставщики данных",
                    "link": reverse_lazy("admin:core_dataprovider_changelist"),
                },
            ],
        },
        {
            "models": (
                "django_celery_beat.periodictask",
                "django_celery_beat.crontabschedule",
                "django_celery_beat.intervalschedule",
                "django_celery_beat.solarschedule",
                "django_celery_beat.clockedschedule",
            ),
            "items": [
                {
                    "title": "Периодические задачи",
                    "link": reverse_lazy("admin:django_celery_beat_periodictask_changelist"),
                },
                {
                    "title": "Cron-графики",
                    "link": reverse_lazy("admin:django_celery_beat_crontabschedule_changelist"),
                },
                {
                    "title": "Интервалы",
                    "link": reverse_lazy("admin:django_celery_beat_intervalschedule_changelist"),
                },
                {
                    "title": "Солнечные графики",
                    "link": reverse_lazy("admin:django_celery_beat_solarschedule_changelist"),
                },
                {
                    "title": "Графики по времени",
                    "link": reverse_lazy("admin:django_celery_beat_clockedschedule_changelist"),
                },
            ],
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Организации и пользователи",
                "collapsible": True,
                "items": [
                    {
                        "title": "Организации",
                        "icon": "business",
                        "link": reverse_lazy("admin:core_organization_changelist"),
                    },
                    {
                        "title": "Пользователи",
                        "icon": "person",
                        "link": reverse_lazy("admin:core_orguser_changelist"),
                    },
                    {
                        "title": "Запросы отчетов",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:core_reportquery_changelist"),
                    },
                    {
                        "title": "Медиафайлы",
                        "icon": "image",
                        "link": reverse_lazy("admin:core_media_changelist"),
                    },
                ],
            },
            {
                "title": "Автомобили и водители",
                "collapsible": True,
                "items": [
                    {
                        "title": "Автомобили",
                        "icon": "car_repair",
                        "link": reverse_lazy("admin:core_car_changelist"),
                    },
                    {
                        "title": "Отчеты об автомобилях",
                        "icon": "report_problem",
                        "link": reverse_lazy("admin:core_carreport_changelist"),
                    },
                    {
                        "title": "Расход топлива",
                        "icon": "local_gas_station",
                        "link": reverse_lazy("admin:core_carconsumption_changelist"),
                    },
                    {
                        "title": "Водители",
                        "icon": "drive_eta",
                        "link": reverse_lazy("admin:core_driver_changelist"),
                    },
                    {
                        "title": "Назначения водителей-автомобилей",
                        "icon": "link",
                        "link": reverse_lazy("admin:core_drivercar_changelist"),
                    },
                ],
            },
            {
                "title": "Данные",
                "collapsible": True,
                "items": [
                    {
                        "title": "Поставщики данных",
                        "icon": "cloud",
                        "link": reverse_lazy("admin:core_dataprovider_changelist"),
                    },
                ],
            },
            {
                "title": "Задачи Celery",
                "collapsible": True,
                "items": [
                    {
                        "title": "Периодические задачи",
                        "icon": "task",
                        "link": reverse_lazy("admin:django_celery_beat_periodictask_changelist"),
                    },
                    {
                        "title": "Cron-графики",
                        "icon": "update",
                        "link": reverse_lazy("admin:django_celery_beat_crontabschedule_changelist"),
                    },
                    {
                        "title": "Интервалы",
                        "icon": "arrow_range",
                        "link": reverse_lazy("admin:django_celery_beat_intervalschedule_changelist"),
                    },
                    {
                        "title": "Солнечные графики",
                        "icon": "sunny",
                        "link": reverse_lazy("admin:django_celery_beat_solarschedule_changelist"),
                    },
                    {
                        "title": "Графики по времени",
                        "icon": "schedule",
                        "link": reverse_lazy("admin:django_celery_beat_clockedschedule_changelist"),
                    },
                ],
            },
        ],
    },
}

INFLUXDB_CONFIG = {
    'URL': os.getenv('INFLUXDB_URL', 'http://fuel-patrol-influxdb:8086'),
    'TOKEN': os.getenv('INFLUXDB_TOKEN', 'your-default-token-here'),
    'ORG': os.getenv('INFLUXDB_ORG', 'fuel_patrol'),
    'BUCKET': os.getenv('INFLUXDB_BUCKET', 'test_fuel'),
    'TIMEOUT': int(os.getenv('INFLUXDB_TIMEOUT', '10000')),
    'WRITE_OPTIONS': {
        'batch_size': int(os.getenv('INFLUXDB_BATCH_SIZE', '1000')),
        'flush_interval': int(os.getenv('INFLUXDB_FLUSH_INTERVAL', '1000')),
    }
}


# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'Введите токен в формате: Bearer <токен>',
        }
    },
    'USE_SESSION_AUTH': False,  # Отключаем сессионную аутентификацию
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Используем JWT
        'rest_framework.authentication.SessionAuthentication',  # Опционально, для админки
        'rest_framework.authentication.BasicAuthentication',  # Опционально
    ],
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=4),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=12),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Custom user model
AUTH_USER_MODEL = 'core.OrgUser'

APPEND_SLASH=False

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000